Revert "Explicitly search optarg and optind in namespace covise"
This reverts commit 25529e8a85bdfe4c138b558055954d997bf30009.

Reason: optind and optarg in global namespace are part of the getopt API as documented in getopt(3).

Also breaks compilation:
src/tools/map_converter/MapConverter.cpp:111:26: error: definition or redeclaration of 'optarg' not allowed inside a function
    extern char *covise::optarg;
                 ~~~~~~~~^
src/tools/map_converter/MapConverter.cpp:111:26: error: no member named 'optarg' in namespace 'covise'
    extern char *covise::optarg;